# 公共配置文件
server:
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  freemarker:
    check-template-location: false
  application:
    name: iusine
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/juzhi_search
    username: root
    password: root
  # Redis 配置
  redis:
      host: localhost
      port: 6379
      password:
      connect-timeout: 5000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 自动转化驼峰风格
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 接口文档配置
springdoc:
  api-docs:
    enabled: true # 是否启用接口文档
knife4j:
  enable: true